# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu_constraint.xdc

# Block Designs: bd/cpu/cpu.bd
# Block Designs: The module: 'cpu' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/cpu/ip/cpu_pc_0_0/cpu_pc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_pc_0_0 || ORIG_REF_NAME==cpu_pc_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_four_0_0/cpu_four_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_four_0_0 || ORIG_REF_NAME==cpu_four_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_lshift2_26_0_0/cpu_lshift2_26_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_lshift2_26_0_0 || ORIG_REF_NAME==cpu_lshift2_26_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_jExtend_0_0/cpu_jExtend_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_jExtend_0_0 || ORIG_REF_NAME==cpu_jExtend_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_szExtend_0_0/cpu_szExtend_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_szExtend_0_0 || ORIG_REF_NAME==cpu_szExtend_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_add_0_0/cpu_add_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_add_0_0 || ORIG_REF_NAME==cpu_add_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_insMem_0_0/cpu_insMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_insMem_0_0 || ORIG_REF_NAME==cpu_insMem_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_addBranch_0_0/cpu_addBranch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_addBranch_0_0 || ORIG_REF_NAME==cpu_addBranch_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_lShift2_0_0/cpu_lShift2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_lShift2_0_0 || ORIG_REF_NAME==cpu_lShift2_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_ctrlUnit_0_0/cpu_ctrlUnit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_ctrlUnit_0_0 || ORIG_REF_NAME==cpu_ctrlUnit_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_regFile_0_0/cpu_regFile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_regFile_0_0 || ORIG_REF_NAME==cpu_regFile_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_pick21_32_5_0_0/cpu_pick21_32_5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_pick21_32_5_0_0 || ORIG_REF_NAME==cpu_pick21_32_5_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_alu_0_0/cpu_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_alu_0_0 || ORIG_REF_NAME==cpu_alu_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_pick21_32_0_0/cpu_pick21_32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_pick21_32_0_0 || ORIG_REF_NAME==cpu_pick21_32_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_pick41_0_0/cpu_pick41_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_pick41_0_0 || ORIG_REF_NAME==cpu_pick41_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_pick21_32_1_0/cpu_pick21_32_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_pick21_32_1_0 || ORIG_REF_NAME==cpu_pick21_32_1_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_dataMem_0_0/cpu_dataMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_dataMem_0_0 || ORIG_REF_NAME==cpu_dataMem_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_clock_0_0/cpu_clock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_clock_0_0 || ORIG_REF_NAME==cpu_clock_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_show_0_0/cpu_show_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_show_0_0 || ORIG_REF_NAME==cpu_show_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_pick_data_0_0/cpu_pick_data_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_pick_data_0_0 || ORIG_REF_NAME==cpu_pick_data_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_led_0_0/cpu_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_led_0_0 || ORIG_REF_NAME==cpu_led_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_clk_divide_0_0/cpu_clk_divide_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_clk_divide_0_0 || ORIG_REF_NAME==cpu_clk_divide_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_IR_0_0/cpu_IR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_IR_0_0 || ORIG_REF_NAME==cpu_IR_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_transtate_0_0/cpu_transtate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_transtate_0_0 || ORIG_REF_NAME==cpu_transtate_0_0} -quiet] -quiet

# XDC: bd/cpu/cpu_ooc.xdc
